### ISSUE TITLE
internal git accessing/ clone function does not work

### ISSUE THREAD

**Issue by skprasadu** [jboss-dockerfiles/jbpm#10]
I am working on windows version of docker. I was able to start jbpm-workbench and work with it like a charm. I did set all the port forwardings to 8080, 8001. When I did git clone, I ran into an issue and followed this JIRA [issues in JIRA](https://issues.jboss.org/browse/RHBRMS-243) and tried again

`git clone ssh://krisv@localhost:8001/jbpm-playground

I get below error:

`Warning: Permanently added '[localhost]:8001' (DSA) to the list of known hosts.
Password authentication
Password authentication
Password authentication
Permission denied, please try again.
Permission denied, please try again.
Permission denied (password,keyboard-interactive).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 `

I poured to google and found one more articles @ http://stackoverflow.com/questions/26118850/drools-workbench-accessing-repository-via-ssh  and I also followed this. I am wondering how to proceed on this.

Please help.

Krishna

**Comment by mbiarnes** [comment]
Hi Krishna,

Could you please check following things:
1. When running the docker image, can you access as krisv/krisv?
2. Did you run exactly 
docker run -p 8080:8080 -p 8001:8001 -t -i --name jbpm-workbench jboss/jbpm-workbench-showcase:latest

Can you look if you can install this without docker? I mean download the war from http://download.jboss.org/drools/release/6.4.0.Final/kie-drools-wb-distribution-wars-6.4.0.Final-wildfly8.war and deploythis war in a wildfly 8 container, create a user like krisv and then try to clone after you started the Wildfly?
We did it here and it worked properly. We think this his nothing to do with docker; maybe with Windows environment? 

Michael
