### ISSUE TITLE
JBPM showcase latest: Could not start 'default' listener.

### ISSUE THREAD

**Issue by aboullaite** [jboss-dockerfiles/jbpm#19]
Hi I just tried to pull and run the latest version of JBPM, with the very old command: 

    docker run -p 8080:8080 -p 8001:8001 -d --name jbpm-workbench jboss/jbpm-workbench-showcase:latest

But the container do not start, and the logs shows that wildfly trigger : `Could not start 'default' listener.`.
I'm running Docker community edition (mac):
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

The complete log:

        Running jBPM Workbench on JBoss Wildfly...
        JAVA_OPTS already set in environment; overriding default settings with values: -Xms256m -Xmx512m
        =========================================================================

          JBoss Bootstrap Environment

          JBOSS_HOME: /opt/jboss/wildfly

          JAVA: /usr/lib/jvm/java/bin/java

          JAVA_OPTS:  -server -Xms256m -Xmx512m

        =========================================================================

        [0m10:03:31,115 INFO  [org.jboss.modules] (main) JBoss Modules version 1.5.2.Final
        [0m[0m10:03:31,340 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.6.Final
        [0m[0m10:03:31,443 INFO  [org.jboss.as] (MSC service thread 1-6) WFLYSRV0049: WildFly Full 10.1.0.Final (WildFly Core 2.2.0.Final) starting
        [0m[0m10:03:33,011 INFO  [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) WFLYDS0004: Found jbpm-console.war in deployment directory. To trigger deployment create a file called jbpm-console.war.dodeploy
        [0m[0m10:03:33,036 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0039: Creating http management service using socket-binding (management-http)
        [0m[0m10:03:33,068 INFO  [org.xnio] (MSC service thread 1-6) XNIO version 3.4.0.Final
        [0m[0m10:03:33,079 INFO  [org.xnio.nio] (MSC service thread 1-6) XNIO NIO Implementation Version 3.4.0.Final
        [0m[0m10:03:33,301 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 41) WFLYCLINF0001: Activating Infinispan subsystem.
        [0m[0m10:03:33,312 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 52) WFLYNAM0001: Activating Naming Subsystem
        [0m[0m10:03:33,317 INFO  [org.wildfly.iiop.openjdk] (ServerService Thread Pool -- 42) WFLYIIOP0001: Activating IIOP Subsystem
        [0m[0m10:03:33,324 INFO  [org.wildfly.extension.io] (ServerService Thread Pool -- 40) WFLYIO001: Worker 'default' has auto-configured to 8 core threads with 64 task threads based on your 4 available processors
        [0m[0m10:03:33,372 INFO  [org.jboss.as.jsf] (ServerService Thread Pool -- 48) WFLYJSF0007: Activated the following JSF Implementations: [main]
        [0m[0m10:03:33,383 INFO  [org.jboss.as.security] (ServerService Thread Pool -- 59) WFLYSEC0002: Activating Security Subsystem
        [0m[0m10:03:33,384 INFO  [org.jboss.as.webservices] (ServerService Thread Pool -- 62) WFLYWS0002: Activating WebServices Extension
        [0m[0m10:03:33,391 INFO  [org.jboss.as.connector] (MSC service thread 1-3) WFLYJCA0009: Starting JCA Subsystem (WildFly/IronJacamar 1.3.4.Final)
        [0m[33m10:03:33,400 WARN  [org.jboss.as.txn] (ServerService Thread Pool -- 60) WFLYTX0013: Node identifier property is set to the default value. Please make sure it is unique.
        [0m[0m10:03:33,401 INFO  [org.jboss.remoting] (MSC service thread 1-6) JBoss Remoting version 4.0.21.Final
        [0m[0m10:03:33,435 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 36) WFLYJCA0004: Deploying JDBC-compliant driver class org.h2.Driver (version 1.3)
        [0m[0m10:03:33,438 INFO  [org.jboss.as.security] (MSC service thread 1-7) WFLYSEC0001: Current PicketBox version=4.9.6.Final
        [0m[0m10:03:33,444 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-5) WFLYJCA0018: Started Driver service with driver-name = h2
        [0m[0m10:03:33,514 INFO  [org.jboss.as.naming] (MSC service thread 1-1) WFLYNAM0003: Starting Naming Service
        [0m[0m10:03:33,517 INFO  [org.jboss.as.mail.extension] (MSC service thread 1-2) WFLYMAIL0001: Bound mail session [java:jboss/mail/Default]
        [0m[0m10:03:33,606 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0003: Undertow 1.4.0.Final starting
        [0m[0m10:03:33,719 INFO  [org.jboss.as.ejb3] (MSC service thread 1-7) WFLYEJB0481: Strict pool slsb-strict-max-pool is using a max instance size of 64 (per class), which is derived from thread worker pool sizing.
        [0m[0m10:03:33,719 INFO  [org.jboss.as.ejb3] (MSC service thread 1-3) WFLYEJB0482: Strict pool mdb-strict-max-pool is using a max instance size of 16 (per class), which is derived from the number of CPUs on this host.
        [0m[0m10:03:33,746 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 61) WFLYUT0014: Creating file handler for path '/opt/jboss/wildfly/welcome-content' with options [directory-listing: 'false', follow-symlink: 'false', case-sensitive: 'true', safe-symlink-paths: '[]']
        [0m[0m10:03:33,754 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0012: Started server default-server.
        [0m[0m10:03:33,764 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0018: Host default-host starting
        [0m[31m10:03:33,867 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service jboss.undertow.listener.default: org.jboss.msc.service.StartException in service jboss.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.
        	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:153)
        	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
        	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
        	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        	at java.lang.Thread.run(Thread.java:748)
        Caused by: java.net.SocketException: Protocol family unavailable
        	at sun.nio.ch.Net.bind0(Native Method)
        	at sun.nio.ch.Net.bind(Net.java:433)
        	at sun.nio.ch.Net.bind(Net.java:425)
        	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
        	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
        	at org.wildfly.extension.undertow.HttpListenerService.startListening(HttpListenerService.java:126)
        	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:142)
        	... 5 more

        [0m[0m10:03:34,112 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-5) WFLYJCA0001: Bound data source [java:jboss/datasources/ExampleDS]
        [0m[0m10:03:34,191 INFO  [org.wildfly.iiop.openjdk] (MSC service thread 1-8) WFLYIIOP0009: CORBA ORB Service started
        [0m[0m10:03:34,207 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-1) WFLYDS0013: Started FileSystemDeploymentService for directory /opt/jboss/wildfly/standalone/deployments
        [0m[0m10:03:34,224 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0027: Starting deployment of "jbpm-console.war" (runtime-name: "jbpm-console.war")
        [0m[0m10:03:34,430 INFO  [org.infinispan.factories.GlobalComponentRegistry] (MSC service thread 1-5) ISPN000128: Infinispan version: Infinispan 'Chakra' 8.2.4.Final
        [0m[0m10:03:34,462 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (ServerService Thread Pool -- 64) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
        [0m[0m10:03:34,463 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (ServerService Thread Pool -- 64) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
        [0m[0m10:03:34,483 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (ServerService Thread Pool -- 66) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
        [0m[0m10:03:34,484 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (ServerService Thread Pool -- 66) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
        [0m[33m10:03:40,795 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0059: Class Path entry xml-apis.jar in /opt/jboss/wildfly/standalone/deployments/jbpm-console.war/WEB-INF/lib/serializer-2.7.1.jar  does not point to a valid jar for a Class-Path reference.
        [0m[33m10:03:40,884 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0059: Class Path entry xercesImpl.jar in /opt/jboss/wildfly/standalone/deployments/jbpm-console.war/WEB-INF/lib/xalan-2.7.1.jar  does not point to a valid jar for a Class-Path reference.
        [0m[33m10:03:40,884 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0059: Class Path entry xml-apis.jar in /opt/jboss/wildfly/standalone/deployments/jbpm-console.war/WEB-INF/lib/xalan-2.7.1.jar  does not point to a valid jar for a Class-Path reference.
        [0m[33m10:03:40,885 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0059: Class Path entry serializer.jar in /opt/jboss/wildfly/standalone/deployments/jbpm-console.war/WEB-INF/lib/xalan-2.7.1.jar  does not point to a valid jar for a Class-Path reference.
        [0m[33m10:03:40,920 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0059: Class Path entry jaxb-core.jar in /opt/jboss/wildfly/standalone/deployments/jbpm-console.war/WEB-INF/lib/jaxb-impl-2.2.11.jar  does not point to a valid jar for a Class-Path reference.
        [0m[33m10:03:40,951 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0059: Class Path entry jaxb-api.jar in /opt/jboss/wildfly/standalone/deployments/jbpm-console.war/WEB-INF/lib/jaxb-core-2.2.11.jar  does not point to a valid jar for a Class-Path reference.
        [0m[31m10:03:40,991 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "jbpm-console.war")]) - failure description: {
            "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined,
            "WFLYCTL0288: One or more services were unable to start due to one or more indirect dependencies not being available." => {
                "Services that were unable to start:" => ["jboss.deployment.unit.\"jbpm-console.war\".PARSE"],
                "Services that may be the cause:" => [
                    "jboss.http-upgrade-registry.default",
                    "jboss.remoting.remotingConnectorInfoService.http-remoting-connector"
                ]
            }
        }
        [0m[31m10:03:40,993 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "jsr77")]) - failure description: {
            "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined,
            "WFLYCTL0288: One or more services were unable to start due to one or more indirect dependencies not being available." => {
                "Services that were unable to start:" => ["jboss.jsr77.ejb"],
                "Services that may be the cause:" => [
                    "jboss.http-upgrade-registry.default",
                    "jboss.remoting.remotingConnectorInfoService.http-remoting-connector"
                ]
            }
        }
        [0m[31m10:03:40,995 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "webservices")]) - failure description: {
            "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined,
            "WFLYCTL0288: One or more services were unable to start due to one or more indirect dependencies not being available." => {
                "Services that were unable to start:" => ["jboss.ws.config"],
                "Services that may be the cause:" => [
                    "jboss.http-upgrade-registry.default",
                    "jboss.remoting.remotingConnectorInfoService.http-remoting-connector"
                ]
            }
        }
        [0m[31m10:03:40,997 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
            ("subsystem" => "messaging-activemq"),
            ("server" => "default")
        ]) - failure description: {
            "WFLYCTL0412: Required services that are not installed:" => ["jboss.http-upgrade-registry.default"],
            "WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.messaging-activemq.default is missing [jboss.http-upgrade-registry.default]"],
            "WFLYCTL0288: One or more services were unable to start due to one or more indirect dependencies not being available." => {
                "Services that were unable to start:" => ["jboss.messaging-activemq.default.jms.manager"],
                "Services that may be the cause:" => [
                    "jboss.http-upgrade-registry.default",
                    "jboss.remoting.remotingConnectorInfoService.http-remoting-connector"
                ]
            }
        }
        [0m[31m10:03:40,998 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "ejb3")]) - failure description: {
            "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined,
            "WFLYCTL0288: One or more services were unable to start due to one or more indirect dependencies not being available." => {
                "Services that were unable to start:" => [
                    "jboss.ejb.default-local-ejb-receiver-service",
                    "jboss.ejb3.ejbClientContext.default",
                    "jboss.ejb3.localEjbReceiver.value"
                ],
                "Services that may be the cause:" => [
                    "jboss.http-upgrade-registry.default",
                    "jboss.remoting.remotingConnectorInfoService.http-remoting-connector"
                ]
            }
        }
        [0m[31m10:03:40,999 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
            ("subsystem" => "undertow"),
            ("server" => "default-server"),
            ("http-listener" => "default")
        ]) - failure description: {
            "WFLYCTL0080: Failed services" => {"jboss.undertow.listener.default" => "org.jboss.msc.service.StartException in service jboss.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.
            Caused by: java.net.SocketException: Protocol family unavailable"},
            "WFLYCTL0412: Required services that are not installed:" => ["jboss.undertow.listener.default"],
            "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined
        }
        [0m[31m10:03:40,999 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
            ("subsystem" => "ejb3"),
            ("service" => "remote")
        ]) - failure description: {
            "WFLYCTL0412: Required services that are not installed:" => ["jboss.remoting.remotingConnectorInfoService.http-remoting-connector"],
            "WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.ejb3.connector is missing [jboss.remoting.remotingConnectorInfoService.http-remoting-connector]"]
        }
        [0m[0m10:03:41,018 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 37) WFLYSRV0010: Deployed "jbpm-console.war" (runtime-name : "jbpm-console.war")
        [0m[0m10:03:41,021 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
        WFLYCTL0184:    New missing/unsatisfied dependencies:
              service jboss.http-upgrade-registry.default (missing) dependents: [service jboss.messaging-activemq.default] 
              service jboss.remoting.remotingConnectorInfoService.http-remoting-connector (missing) dependents: [service jboss.ejb3.connector] 
        WFLYCTL0186:   Services which failed to start:      service jboss.undertow.listener.default: org.jboss.msc.service.StartException in service jboss.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.

        [0m[0m10:03:41,121 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
        [0m[0m10:03:41,121 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
        [0m[31m10:03:41,121 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Full 10.1.0.Final (WildFly Core 2.2.0.Final) started (with errors) in 10414ms - Started 330 of 588 services (10 services failed or missing dependencies, 387 services are lazy, passive or on-demand)
        [0m[0m10:03:41,294 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-7) WFLYSRV0028: Stopped deployment jbpm-console.war (runtime-name: jbpm-console.war) in 151ms
        [0m[31m10:03:41,335 ERROR [stderr] (DeploymentScanner-threads - 1) java.io.IOException: Mount point not found
        [0m[31m10:03:41,336 ERROR [stderr] (DeploymentScanner-threads - 1) 	at sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:91)
        [0m[31m10:03:41,336 ERROR [stderr] (DeploymentScanner-threads - 1) 	at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:65)
        [0m[31m10:03:41,337 ERROR [stderr] (DeploymentScanner-threads - 1) 	at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:44)
        [0m[31m10:03:41,337 ERROR [stderr] (DeploymentScanner-threads - 1) 	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51)
        [0m[31m10:03:41,338 ERROR [stderr] (DeploymentScanner-threads - 1) 	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39)
        [0m[31m10:03:41,339 ERROR [stderr] (DeploymentScanner-threads - 1) 	at sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:368)
        [0m[31m10:03:41,339 ERROR [stderr] (DeploymentScanner-threads - 1) 	at java.nio.file.Files.getFileStore(Files.java:1461)
        [0m[31m10:03:41,340 ERROR [stderr] (DeploymentScanner-threads - 1) 	at org.jboss.as.controller.persistence.FilePersistenceUtils.getPosixAttributes(FilePersistenceUtils.java:124)
        [0m[31m10:03:41,340 ERROR [stderr] (DeploymentScanner-threads - 1) 	at org.jboss.as.controller.persistence.FilePersistenceUtils.createTempFileWithAttributes(FilePersistenceUtils.java:112)
        [0m[31m10:03:41,341 ERROR [stderr] (DeploymentScanner-threads - 1) 	at org.jboss.as.controller.persistence.FilePersistenceUtils.writeToTempFile(FilePersistenceUtils.java:99)
        [0m[31m10:03:41,341 ERROR [stderr] (DeploymentScanner-threads - 1) 	at org.jboss.as.controller.persistence.ConfigurationFilePersistenceResource.doCommit(ConfigurationFilePersistenceResource.java:55)
        [0m[31m10:03:41,342 ERROR [stderr] (DeploymentScanner-threads - 1) 	at org.jboss.as.controller.persistence.AbstractFilePersistenceResource.commit(AbstractFilePersistenceResource.java:58)
        [0m[31m10:03:41,342 ERROR [stderr] (DeploymentScanner-threads - 1) 	at org.jboss.as.controller.ModelControllerImpl$4.commit(ModelControllerImpl.java:789)
        [0m[31m10:03:41,343 ERROR [stderr] (DeploymentScanner-threads - 1) 	at org.jboss.as.controller.AbstractOperationContext.executeDoneStage(AbstractOperationContext.java:743)
        [0m[31m10:03:41,343 ERROR [stderr] (DeploymentScanner-threads - 1) 	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:680)
        [0m[31m10:03:41,343 ERROR [stderr] (DeploymentScanner-threads - 1) 	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370)
        [0m[31m10:03:41,344 ERROR [stderr] (DeploymentScanner-threads - 1) 	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1329)
        [0m[31m10:03:41,344 ERROR [stderr] (DeploymentScanner-threads - 1) 	at org.jboss.as.controller.ModelControllerImpl.internalExecute(ModelControllerImpl.java:400)
        [0m[31m10:03:41,344 ERROR [stderr] (DeploymentScanner-threads - 1) 	at org.jboss.as.controller.ModelControllerImpl.execute(ModelControllerImpl.java:222)
        [0m[31m10:03:41,344 ERROR [stderr] (DeploymentScanner-threads - 1) 	at org.jboss.as.controller.ModelControllerImpl$3$1$1.run(ModelControllerImpl.java:756)
        [0m[31m10:03:41,345 ERROR [stderr] (DeploymentScanner-threads - 1) 	at org.jboss.as.controller.ModelControllerImpl$3$1$1.run(ModelControllerImpl.java:750)
        [0m[31m10:03:41,345 ERROR [stderr] (DeploymentScanner-threads - 1) 	at java.security.AccessController.doPrivileged(Native Method)
        [0m[31m10:03:41,345 ERROR [stderr] (DeploymentScanner-threads - 1) 	at org.jboss.as.controller.ModelControllerImpl$3$1.run(ModelControllerImpl.java:750)
        [0m[31m10:03:41,346 ERROR [stderr] (DeploymentScanner-threads - 1) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        [0m[31m10:03:41,346 ERROR [stderr] (DeploymentScanner-threads - 1) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        [0m[31m10:03:41,346 ERROR [stderr] (DeploymentScanner-threads - 1) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        [0m[31m10:03:41,347 ERROR [stderr] (DeploymentScanner-threads - 1) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        [0m[31m10:03:41,347 ERROR [stderr] (DeploymentScanner-threads - 1) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        [0m[31m10:03:41,347 ERROR [stderr] (DeploymentScanner-threads - 1) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        [0m[31m10:03:41,347 ERROR [stderr] (DeploymentScanner-threads - 1) 	at java.lang.Thread.run(Thread.java:748)
        [0m[31m10:03:41,348 ERROR [stderr] (DeploymentScanner-threads - 1) 	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
        [0m[33m10:03:41,363 WARN  [org.jboss.as.controller] (DeploymentScanner-threads - 1) WFLYCTL0357: Notification of type deployment-undeployed is not described for the resource at the address []
        [0m[0m10:03:41,364 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 1) WFLYSRV0009: Undeployed "jbpm-console.war" (runtime-name: "jbpm-console.war")
        [0m[0m10:03:41,364 INFO  [org.jboss.as.controller] (DeploymentScanner-threads - 1) WFLYCTL0183: Service status report
        WFLYCTL0186:   Services which failed to start:      service jboss.undertow.listener.default: org.jboss.msc.service.StartException in service jboss.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.

        [0m[0m10:03:46,071 INFO  [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) WFLYDS0004: Found jbpm-console.war in deployment directory. To trigger deployment create a file called jbpm-console.war.dodeploy
        [0m

**Comment by mbiarnes** [comment]
I did the same on my local, and it worked.
docker run -i -t -p 8080:8080 -p 8001:8001  --name jbpm-workbench jboss/jbpm-workbench-showcase:latest
I use docker Docker version 1.8.2-fc22, build cb216be/1.8.2

**Comment by aboullaite** [comment]
Pulled the latest version again, But no chance ! still same issue

**Comment by ghost** [comment]
The same for me.
Docker Community Edition
Version 17.06.1-ce-win24 (13025)

but
4.12.8-2-ARCH linux
Docker version 17.06.0-ce, build 3dfb8343
works!

**Comment by ghost** [comment]
Seems to work better - I pulled the image today morning and first start failed second attempt works (Docker Version 17.06.1-ce-win24 ).
Thanks

[logs.txt](https://github.com/jboss-dockerfiles/jbpm/files/1245035/logs.txt)

**Comment by vinisxs** [comment]
I had the same problem and solved as suggested here: https://github.com/jboss-dockerfiles/jbpm/issues/15#issue-222180132

**Comment by cosmocracy** [comment]
Failing "out of box" for me, too.

**Comment by cosmocracy** [comment]
Spot on, @vipseixas I was able to get it started by adding the following to the end of my `JAVA_OPTS` variable: `-Djava.net.preferIPv4Stack=true` when starting the container.
