### ISSUE TITLE
java.net.UnknownHostException: repo.maven.apache.org

### ISSUE THREAD

**Issue by njc123** [jboss-dockerfiles/jbpm#24]
Can anyone help me with this error I see in server.log, with what appears to be the mysql and postgresql driver modules not being found?  I attached the server.log.  The container seems to otherwise be starting up properly.

[server.log](https://github.com/jboss-dockerfiles/jbpm/files/1507831/server.log)

Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.postgresql:postgresql:pom:9.4.1207 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org

[jboss@moby org]$ pwd
/opt/jboss/wildfly/modules/system/layers/base/org

[jboss@moby org]$ ls
antlr   bouncycastle  dom4j    fusesource  hibernate  infinispan  jaxen   jboss  jgroups  jsoup  opensaml   picketlink  wildfly
apache  codehaus      eclipse  glassfish   hornetq    javassist   jberet  jdom   joda     omg    picketbox  slf4j       yaml

**Comment by mbiarnes** [comment]
Hi,
When your docker container has not access to internet you will see this "error". But this is not a serious error, you can ignore it. In the new version 7.5.0.Final there is a new parameter (-Ddatasource.management.disableDefaultDrivers=true) that prevents to try to download datasource drivers.
