### ISSUE TITLE
No Repository and Organization editors into Workbench

### ISSUE THREAD

**Issue by akarasev** [jboss-dockerfiles/jbpm#28]
There are should be [Repoistory editor](https://docs.jboss.org/jbpm/release/7.5.0.Final/jbpm-docs/html_single/#_wb.vfsrepository) and [Orgaionzation Unit Manager](https://docs.jboss.org/jbpm/release/7.5.0.Final/jbpm-docs/html_single/#_wb.organizationalunit), but they are absent.

Could somebody explain how to find or enable those items?

**Comment by mbiarnes** [comment]
both have gone

**Comment by akarasev** [comment]
Are you saying official documentation is not up to date and it's not possible to checkout private repositories and choose a specific branch?

**Comment by mbiarnes** [comment]
Please ask  your specific questions at https://groups.google.com/forum/#!forum/drools-setup or https://groups.google.com/forum/#!forum/drools-usage, maybe there is a better response

**Comment by akarasev** [comment]
Thank you!
