### ISSUE TITLE
sudo root password

### ISSUE THREAD

**Issue by eddo888** [jboss-dockerfiles/jbpm#3]
Hi, Love this docker image, I would love to be able to install some other unix applications
and could you please tell me the sudo su root password.
you can SMS it to me on [REDACTED] if your don't want it public.

Many Thanks
Dave.

**Comment by goldmann** [comment]
This is a Docker image, so you don't need any password, just run the container as root (if this is what you want): `docker run -it -u root jboss/jbpm-workbench:6.2.0.Final bash`. Please note that this will not start the process itself. You probably want to learn more about Docker: http://docs.docker.com/mac/step_two/.

P.S. I don't think it's a good idea to give your phone # publicly, so I'll remove it from this issue.
