### ISSUE TITLE
Unable to run the docker container with jbpm 6.5.0.Final

### ISSUE THREAD

**Issue by avnsiva** [jboss-dockerfiles/jbpm#31]
Hi,

I want to download the docker image which contains the jbpm version 6.5.0.Final from docker hub.
But unfortunately I am unable to do it. The docker hub contains only the latest version. Can you please help me how to run the docker image which contains the jbpm 6.5.0.Final?

**Comment by mbiarnes** [comment]
try: docker pull jboss/jbpm-workbench:6.5.0.Final for the 6.5.0.Final tag.
All available tags you see here: https://hub.docker.com/r/jboss/jbpm-workbench/tags/
