### ISSUE TITLE
Workbench LDAP integration

### ISSUE THREAD

**Issue by dukechandu** [jboss-dockerfiles/jbpm#36]
Hi,

Can any one help me in integrating LDAP with workbench (7.6.0/7.7.0) using custom role 'APP_TEST' using tomcat. 

Thanks
Chandra.

**Comment by mbiarnes** [comment]
Hi,

Please enjoy the lists [drools-setup](https://groups.google.com/forum/#!forum/drools-setup) or
[drools-usage](https://groups.google.com/forum/#!forum/drools-usage) for questions related to questions not related to docker. More people are reading these lists.
