### ISSUE TITLE
Feature request add kie config cli

### ISSUE THREAD

**Issue by xrow** [jboss-dockerfiles/jbpm#4]
Hi,

I was looking at the delivery. I was wondering, if it would make sense to ass teh kie config cli to the docker container?

**Comment by romartin** [comment]
Hey! Do you mind moving this conversation to the Drools Usage google groups (https://groups.google.com/forum/#!forum/drools-usage), so other core team developers can participate? I'm not an expert of the kie config cli feature sorry.

**Comment by xrow** [comment]
Not at all! Though I might have a solution for this problem.

I added this to the Dockerfile.

```
####### JBPM-CLI ############
RUN curl -o /opt/jboss/$KIE_CLI_CONTEXT_PATH.zip $KIE_REPOSITORY/org/kie/$KIE_CLI_CONTEXT_PATH/$JBPM_VERSION/$KIE_CLI_CONTEXT_PATH-$JBPM_VERSION-dist.zip && \
unzip -q /opt/jboss/$KIE_CLI_CONTEXT_PATH.zip -d /opt/jboss/$KIE_CLI_CONTEXT &&  \ 
rm -rf /opt/jboss/$KIE_CLI_CONTEXT_PATH.zip
```

Shall I create a pull request?

**Comment by romartin** [comment]
I don't think we are going to include it by default in the docker image. The CLI feature shall be used from whatever machine you like as it does connect to git server over ssh so as long as GIT server of the workbench is setup properly (on host name and port that docker is exposing) then kie-config-cli will be able to connect to it remotely. 

Thanks anyway!!
